dns_master:
  hosts:
    gandalf:
      ansible_port: 22
      ansible_host: 10.0.0.10
dns_slave:
  hosts:
    sauron:
      ansible_port: 22
      ansible_host: 10.0.0.8
dns_server:
  children:
    dns_master:
    dns_slave:
