---
bind9_packages:
  - bind9
  - bind9utils
  - bind9-dnsutils
  - bind9-doc
  - bind9-host

# Logging
bind9_named_logging: True
bind9_log_path: /var/log/bind
bind9_lib_path: /var/lib/bind
bind9_log_severity: info  # critical | error | warning | notice | info | debug [ level ] | dynamic
bind9_log_versions: 3

search_domain: "{{ main_domain }}"

# Indicate whether the main domain zone files must be reapplied (loosing DDNS registrations)
install_zone_files: false