---
- name: restart bind9
  service:
    name: bind9
    state: restarted

- name: reload bind9
  service:
    name: bind9
    state: reloaded

- name: resync zones
  ansible.builtin.shell: "rndc sync {{search_domain}} && rndc freeze {{search_domain}} && rndc reload {{search_domain}} && rndc thaw {{search_domain}}"
  register: resync
