---
- name: restart bind9
  service:
    name: bind9
    state: restarted

- name: reload bind9
  service:
    name: bind9
    state: reloaded

- name: resync zones
  ansible.builtin.shell: 'rndc sync --clean'
  register: resync

- name: Reboot Linux
  reboot:
    reboot_timeout: 300
  register: reboot
